import type { QuizQuestion } from "@/types";

export const CHAPTER_QUIZZES: Record<string, QuizQuestion[]> = {
  "rj-prologue": [
    {
      id: "rj-p-1",
      type: "multiple_choice",
      question: "What city is Romeo and Juliet set in?",
      options: ["Venice", "Verona", "Rome", "Florence"],
      correctAnswer: "Verona",
      explanation: 'The Prologue states "In fair Verona, where we lay our scene."',
    },
    {
      id: "rj-p-2",
      type: "true_false",
      question: "The two households mentioned in the Prologue are allies.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: 'They have an "ancient grudge" \u2014 they are bitter enemies.',
    },
    {
      id: "rj-p-3",
      type: "multiple_choice",
      question: 'What does "star-cross\'d" mean in the context of the lovers?',
      options: [
        "They are blessed by the stars",
        "Their fate is doomed by destiny",
        "They travel at night",
        "They are famous celebrities",
      ],
      correctAnswer: "Their fate is doomed by destiny",
      explanation: '"Star-cross\'d" means their love is fated to end in tragedy, as if the stars are working against them.',
    },
    {
      id: "rj-p-4",
      type: "multiple_choice",
      question: "What ultimately ends the feud between the two families?",
      options: [
        "A peace treaty",
        "The death of their children",
        "A royal decree",
        "A marriage alliance",
      ],
      correctAnswer: "The death of their children",
      explanation: 'The Prologue tells us "with their death bury their parents\' strife" \u2014 only the children\'s deaths end the hatred.',
    },
    {
      id: "rj-p-5",
      type: "true_false",
      question: "The Prologue is written as a sonnet (14 lines).",
      options: ["True", "False"],
      correctAnswer: "True",
      explanation: "The Prologue is indeed a 14-line Shakespearean sonnet with an ABAB CDCD EFEF GG rhyme scheme.",
    },
  ],

  "rj-act1-scene1": [
    {
      id: "rj-1-1",
      type: "multiple_choice",
      question: "Which family do Sampson and Gregory serve?",
      options: ["Montague", "Capulet", "The Prince", "Neither"],
      correctAnswer: "Capulet",
      explanation: "Sampson and Gregory are servants of the Capulet household.",
    },
    {
      id: "rj-1-2",
      type: "multiple_choice",
      question: 'What does "bite my thumb" mean in this context?',
      options: [
        "A sign of respect",
        "A rude, insulting gesture",
        "A greeting between friends",
        "A sign of nervousness",
      ],
      correctAnswer: "A rude, insulting gesture",
      explanation: "Biting one's thumb was an insulting gesture in Elizabethan England, similar to giving someone the finger today.",
    },
    {
      id: "rj-1-3",
      type: "true_false",
      question: "Sampson directly admits to biting his thumb AT Abraham.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: 'Sampson carefully says "I do bite my thumb, sir" but when pressed, denies doing it specifically at Abraham \u2014 to avoid starting an illegal fight.',
    },
    {
      id: "rj-1-4",
      type: "multiple_choice",
      question: "Why does Sampson check with Gregory before answering Abraham?",
      options: [
        "He forgot the answer",
        "He wants to know if the law is on their side",
        "He is scared of Abraham",
        "Gregory is his boss",
      ],
      correctAnswer: "He wants to know if the law is on their side",
      explanation: 'Sampson asks "Is the law of our side, if I say ay?" \u2014 he wants to provoke a fight without being the one who legally starts it.',
    },
  ],

  "rj-act2-scene2": [
    {
      id: "rj-2-1",
      type: "multiple_choice",
      question: 'What does Romeo compare Juliet to when he says "It is the east"?',
      options: ["The moon", "The sun", "A star", "The dawn"],
      correctAnswer: "The sun",
      explanation: '"It is the east, and Juliet is the sun" \u2014 Romeo compares Juliet to the sun rising in the east.',
    },
    {
      id: "rj-2-2",
      type: "multiple_choice",
      question: 'When Juliet says "wherefore art thou Romeo," what is she asking?',
      options: [
        "Where is Romeo?",
        "Why is his name Romeo (a Montague)?",
        "Who is Romeo?",
        "How did Romeo get here?",
      ],
      correctAnswer: "Why is his name Romeo (a Montague)?",
      explanation: '"Wherefore" means "why," not "where." Juliet is lamenting that the man she loves belongs to her family\'s enemy.',
    },
    {
      id: "rj-2-3",
      type: "multiple_choice",
      question: 'What point is Juliet making with the "rose by any other name" speech?',
      options: [
        "She prefers roses to other flowers",
        "Names are meaningless \u2014 Romeo would be the same person without the Montague name",
        "She wants to plant a garden",
        "She thinks Romeo should change his first name",
      ],
      correctAnswer: "Names are meaningless \u2014 Romeo would be the same person without the Montague name",
      explanation: "Juliet argues that a name is just a label. A rose would smell just as sweet even with a different name, and Romeo is still the same person regardless of his family name.",
    },
    {
      id: "rj-2-4",
      type: "true_false",
      question: "Romeo reveals himself to Juliet immediately when she appears on the balcony.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: 'Romeo listens to Juliet\'s soliloquy first, debating with himself ("Shall I hear more, or shall I speak at this?") before revealing himself.',
    },
  ],

  "gg-ch1": [
    {
      id: "gg-1-1",
      type: "multiple_choice",
      question: "Who is the narrator of The Great Gatsby?",
      options: ["Jay Gatsby", "Nick Carraway", "Tom Buchanan", "Daisy Buchanan"],
      correctAnswer: "Nick Carraway",
      explanation: "Nick Carraway narrates the entire novel, telling the story from his perspective.",
    },
    {
      id: "gg-1-2",
      type: "multiple_choice",
      question: "What advice did Nick's father give him?",
      options: [
        "Always tell the truth",
        "Reserve all judgments about people",
        "Work hard and save money",
        "Stay away from New York",
      ],
      correctAnswer: "Reserve all judgments about people",
      explanation: "Nick's father told him not to criticize others because they haven't had the same advantages.",
    },
    {
      id: "gg-1-3",
      type: "true_false",
      question: "Nick says his tolerance for others has no limit.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: 'Nick admits "it has a limit" \u2014 despite trying to reserve judgment, his tolerance is not infinite.',
    },
    {
      id: "gg-1-4",
      type: "multiple_choice",
      question: "Where is the Carraway family from?",
      options: ["The East Coast", "The South", "The Middle West", "California"],
      correctAnswer: "The Middle West",
      explanation: 'Nick says "My family have been prominent, well-to-do people in this Middle Western city for three generations."',
    },
  ],

  "gg-ch2": [
    {
      id: "gg-2-1",
      type: "multiple_choice",
      question: "What is the Valley of Ashes?",
      options: [
        "A wealthy suburb",
        "A desolate, grey wasteland between the Eggs and New York",
        "A beautiful park",
        "Gatsby's neighborhood",
      ],
      correctAnswer: "A desolate, grey wasteland between the Eggs and New York",
      explanation: "The Valley of Ashes is an industrial dumping ground, representing the dark underside of the American Dream.",
    },
    {
      id: "gg-2-2",
      type: "multiple_choice",
      question: "What do the eyes of Doctor T.J. Eckleburg represent on the billboard?",
      options: [
        "An actual eye doctor's advertisement",
        "God watching over a moral wasteland",
        "Gatsby's vision for the future",
        "Nick's judgment of others",
      ],
      correctAnswer: "God watching over a moral wasteland",
      explanation: "While literally an old optometrist's billboard, the giant eyes are widely interpreted as a symbol of God or moral judgment watching over the corruption of the era.",
    },
    {
      id: "gg-2-3",
      type: "true_false",
      question: "Tom Buchanan is faithful to his wife Daisy.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: "Tom is having an affair with Myrtle Wilson, which Nick discovers in Chapter 2.",
    },
  ],

  "frank-letter1": [
    {
      id: "fr-1-1",
      type: "multiple_choice",
      question: "Where is Captain Walton when he writes the first letter?",
      options: ["London", "St. Petersburgh", "The Arctic", "Geneva"],
      correctAnswer: "St. Petersburgh",
      explanation: "Walton writes from St. Petersburgh (St. Petersburg), Russia, before departing for the Arctic.",
    },
    {
      id: "fr-1-2",
      type: "multiple_choice",
      question: "Who is Walton writing to?",
      options: ["Victor Frankenstein", "His sister Margaret", "His captain", "The public"],
      correctAnswer: "His sister Margaret",
      explanation: "The letter is addressed to Mrs. Saville, England \u2014 Walton's sister Margaret.",
    },
    {
      id: "fr-1-3",
      type: "true_false",
      question: "Margaret is enthusiastic about Walton's expedition.",
      options: ["True", "False"],
      correctAnswer: "False",
      explanation: 'Walton mentions that Margaret has regarded his enterprise "with such evil forebodings" \u2014 she fears for his safety.',
    },
  ],
};
